
database:
  name: 'market_list'
#  name: 'postgres'
  host: 'localhost'
  port: '5432'
  username: 'postgres'
  password: 'market-list'
  schema: 'market_list'

server:
  tls:
    enabled: false
    crt: 'server.crt'
    key: 'server.key'
